# Generated by Django 3.1.7 on 2021-03-11 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_remove_binss_bin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='binss',
            name='bin_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
