# Generated by Django 3.1.7 on 2021-03-11 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0005_binss_bin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binss',
            name='bin_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
