# Generated by Django 3.1.7 on 2021-03-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0010_auto_20210311_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binss',
            name='user',
        ),
    ]
