# Generated by Django 3.1.7 on 2021-03-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0015_auto_20210311_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Binss',
        ),
    ]
