# Generated by Django 3.1.7 on 2021-03-14 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bins', '0025_auto_20210312_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binss',
            name='id',
        ),
        migrations.AlterField(
            model_name='binss',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
