# Generated by Django 3.1.7 on 2021-03-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0030_auto_20210315_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Binss',
        ),
    ]
